variables:
    MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test

cache:
    paths:
        - .m2/repository
        - target

build:
    stage: build
    tags:
        - docker
    script:
        - cd Backend
        - echo "Maven compile started"
        - mvn clean compile

test:
    stage: test
    tags:
        - docker
    script:
        - cd Backend
        - echo "Maven test started"
        - mvn clean test
